AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  IAMRoleName:
    Type: String
    Description: The name of the IAM role
    Default: TestRole
  RoleDescription:
    Type: String
    Description: The description of the IAM role
    Default: This role is used for testing purpose.
  # Policies:
  #   Type: CommaDelimitedList
  #   Description: A list of IAM policies to attach to the role

Resources:
  IamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      RoleName: !Ref IAMRoleName
      Description: !Ref RoleDescription
      Policies:
        - PolicyName: test-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                - ec2:*
                Resource: "*"

Outputs:
  RoleArn:
    Value: !GetAtt IamRole.Arn
    Description: The ARN of the IAM role