AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create a static AWS Security Group

Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: The ID of the VPC where the security group will be created.

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "StaticSecurityGroup"
      GroupDescription: "Static security group with hardcoded rules."
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupId:
    Description: ID of the created Security Group
    Value: !Ref SecurityGroup
