AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an S3 bucket
Parameters:
  BucketName:
    Description: 'Specify name of the S3 bucket.'
    Type: String
    Default: my-unique-bucket-name
    
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: MyProject

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket