AWSTemplateFormatVersion: 2010-09-09
Description: This template will create S3 bucket with event notifications.

Parameters:
  QueueArn:
    Type: String
    Description: Specify SQS Queue ARN.
    Default: ''
  BucketName:
    Description: 'Specify name of the S3 bucket.'
    Type: String
    Default: my-unique-bucket-name
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ${BucketName}
      AccessControl: Private
      NotificationConfiguration:
        QueueConfiguration:
          Event: s3:ObjectCreated:*
          # Filter: 
          #   NotificationFilter
          Queue: !Ref QueueArn

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a notification configuration.
  SQSQueue:
    Value: !Ref QueueArn