AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create VPC and Subnets.

Parameters:
  VPCCIDR:
    Type: String
    Description: The CIDR block for the VPC.
    Default: 10.0.0.0/16
  PubSubCIDR:
    Type: String
    Description: The CIDR block for the public subnet.
    Default: 10.0.1.0/24
  PriSubCIDR:
    Type: String
    Description: The CIDR block for the private subnet.
    Default: 10.0.2.0/24
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyApplicationVPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PubSubCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MyPublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PriSubCIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: MyPrivateSubnet

Outputs:
  VPCId:
    Description: The ID of the VPC.
    Value: !Ref MyVPC

  PublicSubnetId:
    Description: The ID of the Public Subnet.
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: The ID of the Private Subnet.
    Value: !Ref PrivateSubnet
