AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to launch an EC2 instance.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type.

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the EC2 key pair.

  VpcId:
    Type: String
    Description: VPC ID.

  SubnetId:
    Type: String
    Description: Subnet ID.
  ImageID:
    Type: String
    Description: Specify ID of the AMI.
    Default: ""

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      ImageId: !Ref ImageID

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance.
    Value: !Ref MyEC2Instance
