AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create SNS Topic.

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: 
            Fn::GetAtt:
              - "MyQueue1"
              - "Arn"
          Protocol: "sqs"
        - Endpoint:
            Fn::GetAtt:
              - "MyQueue2" 
              - "Arn"
          Protocol: "sqs"
      TopicName: "SampleTopic"
    Outputs:
      TopicArn:
        Description: The ARN of the created SNS topic
        Value: !Ref MySNSTopic
      TopicName: 
        Description: The name of the created SNS topic
        Value: "SampleTopic"
          